/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManagedataRouteImport } from './routes/managedata'
import { Route as BulkaddRouteImport } from './routes/bulkadd'
import { Route as BooksRouteImport } from './routes/books'
import { Route as BarcodesRouteImport } from './routes/barcodes'
import { Route as IndexRouteImport } from './routes/index'

const ManagedataRoute = ManagedataRouteImport.update({
  id: '/managedata',
  path: '/managedata',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkaddRoute = BulkaddRouteImport.update({
  id: '/bulkadd',
  path: '/bulkadd',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const BarcodesRoute = BarcodesRouteImport.update({
  id: '/barcodes',
  path: '/barcodes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/barcodes': typeof BarcodesRoute
  '/books': typeof BooksRoute
  '/bulkadd': typeof BulkaddRoute
  '/managedata': typeof ManagedataRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/barcodes': typeof BarcodesRoute
  '/books': typeof BooksRoute
  '/bulkadd': typeof BulkaddRoute
  '/managedata': typeof ManagedataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/barcodes': typeof BarcodesRoute
  '/books': typeof BooksRoute
  '/bulkadd': typeof BulkaddRoute
  '/managedata': typeof ManagedataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/barcodes' | '/books' | '/bulkadd' | '/managedata'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/barcodes' | '/books' | '/bulkadd' | '/managedata'
  id: '__root__' | '/' | '/barcodes' | '/books' | '/bulkadd' | '/managedata'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BarcodesRoute: typeof BarcodesRoute
  BooksRoute: typeof BooksRoute
  BulkaddRoute: typeof BulkaddRoute
  ManagedataRoute: typeof ManagedataRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/managedata': {
      id: '/managedata'
      path: '/managedata'
      fullPath: '/managedata'
      preLoaderRoute: typeof ManagedataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulkadd': {
      id: '/bulkadd'
      path: '/bulkadd'
      fullPath: '/bulkadd'
      preLoaderRoute: typeof BulkaddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barcodes': {
      id: '/barcodes'
      path: '/barcodes'
      fullPath: '/barcodes'
      preLoaderRoute: typeof BarcodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BarcodesRoute: BarcodesRoute,
  BooksRoute: BooksRoute,
  BulkaddRoute: BulkaddRoute,
  ManagedataRoute: ManagedataRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
