/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BulkaddRouteImport } from './routes/bulkadd'
import { Route as IndexRouteImport } from './routes/index'

const BulkaddRoute = BulkaddRouteImport.update({
  id: '/bulkadd',
  path: '/bulkadd',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bulkadd': typeof BulkaddRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bulkadd': typeof BulkaddRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bulkadd': typeof BulkaddRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bulkadd'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bulkadd'
  id: '__root__' | '/' | '/bulkadd'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BulkaddRoute: typeof BulkaddRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/bulkadd': {
      id: '/bulkadd'
      path: '/bulkadd'
      fullPath: '/bulkadd'
      preLoaderRoute: typeof BulkaddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BulkaddRoute: BulkaddRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
