name: Build/release Electron app

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Install RPM tools
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y rpm

      - name: build-linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:linux

      - name: build-win
        if: matrix.os == 'windows-latest'
        run: npm run build:win

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.os }}
          path: dist/*
          if-no-files-found: warn

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6

      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts-ubuntu-latest
          path: dist

      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts-windows-latest
          path: dist

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          body_path: RELEASE_NOTES.md
          generate_release_notes: true
          files: |
            dist/*.exe
            dist/*.msi
            dist/*.zip
            dist/*.dmg
            dist/*.AppImage
            dist/*.snap
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/*.yml
            dist/*.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
